// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDefcN4ObTc6bB1iEvKoJs3QCLBtQjRIRI',
    appId: '1:454910813672:web:02e5c3821eb7c1e0c5b05d',
    messagingSenderId: '454910813672',
    projectId: 'farmcart-ed4c8',
    authDomain: 'farmcart-ed4c8.firebaseapp.com',
    storageBucket: 'farmcart-ed4c8.appspot.com',
    measurementId: 'G-6MTSTWRH7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdjiwD2rlmAxuyn0X7ckgXX9z7-EENHro',
    appId: '1:454910813672:android:cc2de8077d4f9afac5b05d',
    messagingSenderId: '454910813672',
    projectId: 'farmcart-ed4c8',
    storageBucket: 'farmcart-ed4c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMUPx23PsfDaaAyRdgOY45hHL8rkaa3b4',
    appId: '1:454910813672:ios:20d2661db0f154a0c5b05d',
    messagingSenderId: '454910813672',
    projectId: 'farmcart-ed4c8',
    storageBucket: 'farmcart-ed4c8.appspot.com',
    iosBundleId: 'com.example.farmerEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMUPx23PsfDaaAyRdgOY45hHL8rkaa3b4',
    appId: '1:454910813672:ios:19e43c6a1e9940e7c5b05d',
    messagingSenderId: '454910813672',
    projectId: 'farmcart-ed4c8',
    storageBucket: 'farmcart-ed4c8.appspot.com',
    iosBundleId: 'com.example.farmerEcommerce.RunnerTests',
  );
}
